# Site settings
title: Tournamatic Blog
email: blog@tournamatic.com
# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars2.githubusercontent.com/u/9289973?v=3&s=460

description: > # this means to ignore newlines until "baseurl:"
  This is the official blog of tournamatic.com platform. You may find in-depth posts about the platform or short, opinionated posts on anything regarding sports;)
baseurl: "" # the subpath of your site, e.g. /newpath-for-emping
url: "http://blog.tournamatic.com" # the base hostname & protocol for your site
twitter_username: tournamatic
github_username:  tournamatic
GoogleAnalytics: UA-56972385-1

twitter:
  username: tournamatic
facebook:
  app_id: 777108422301894
  publisher: tournamatic

sass:
    style: compressed

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true

gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

defaults:
    - {scope: {type: posts}, values: {layout: post, permalink: '/:title'}}

include:
  - _pages

exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  

